config/routes.rb
StormDispatch::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home"
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/faq',     :to => 'pages#faq'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110521031917
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  first_name         :string(255)
#  last_name          :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#

# == Schema Information
# Schema version: 20110516195437
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  first_name         :string(255)
#  last_name          :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, :presence     => true,
					     :length       => { :maximum => 50 }
  validates :last_name,  :presence     => true,
					     :length       => { :maximum => 50 }
  validates :email, 	 :presence     => true,
					     :format       => { :with => email_regex },
					     :uniqueness   => { :case_sensitive => false }
  validates :password,   :presence     => true,
					     :confirmation => true,
					     :length       => { :within => 6..12 }
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def User.authenticate(email, submitted_password)
    user = User.find_by_email(email)
	return nil  if user.nil?
	return user if user.has_password?(submitted_password)
  end
  
  def User.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
	(user && user.salt == cookie_salt) ? user : nil
  end
  
  private
  
    def encrypt_password
	  self.salt = make_salt if new_record?
	  self.encrypted_password = encrypt(password)
	end
	
	def encrypt(string)
	  secure_hash("#{salt}--#{string}") 
	end
	
	def make_salt
	  secure_hash("#{Time.now.utc}--#{password}")
	end
	
	def secure_hash(string)
	  Digest::SHA2.hexdigest(string)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
	@title = "Home"
  end

  def contact
	@title = "Contact Us"
  end

  def about
	@title = "About Us"
  end
  
  def faq
	@title = "FAQ"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = "Sign In"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
							 params[:session][:password])
	  if user.nil?
	    @title = "Sign In"
      flash.now[:error] = "Invalid email/password combination"
	    render 'new'
	  else
	    sign_in user
	    redirect_back_or user
	  end
  end
  
  def destroy
    sign_out
	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @users = User.paginate(:page => params[:page])
    @title = "ramples users"
  end
  
  def show
    @user  = User.find(params[:id])
	  @title = "#{@user.first_name} #{@user.last_name}"
  end
  
  def new
  	@user  = User.new
    @title = "Sign Up"
  end
  
  def create
	  if @user.save
	    redirect_to @user, :flash => { :success => "Welcome to ramples.com!" }
	    sign_in @user
    else
      @title = "Sign Up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit User"
  end
  
  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :flash => { :success => "Profile udpated." }
    else
      @title = "Edit User"
      render 'edit'
    end
  end
  
  def destroy
    user = User.find(params[:id]).destroy
    redirect_to users_path, :flash => { :success => "User #{user.first_name} #{user.last_name} was deleted." }
  end

  private
  
  def authenticate 
    deny_access unless signed_in?
  end
  
  def correct_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
    user = User.find(params[:id])
    redirect_to(users_path, :flash => {:error =>
                           "Sorry. That action cannot be performed."}) if (!current_user.admin? || current_user?(user))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per page basis
  def title
    base_title = "ramples.com"
	if @title.nil?
	  base_title
	else
	  "#{base_title} | #{@title}"
	end
  end
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
	current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page!"
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
  
  private
  
    def user_from_remember_token
	  User.authenticate_with_salt(*remember_token)
	end
	
	def remember_token
	  cookies.signed[:remember_token] || [nil, nil]
	end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => "#{user.first_name} #{user.last_name}",
											:class => 'gravatar',
											:gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
	<ul>
	  <li><%= link_to "About", about_path %>
	  <li><%= link_to "Contact", contact_path %>
	  <li><%= link_to "FAQ", faq_path %>
	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <% logo = image_tag("ramples_logo.png", :alt => "ramples.com", :class => "round") %>
    <%= link_to logo, root_path %>
  <nav class="round">
	<ul>
	  <li><%= link_to "Home", root_path %></li>
	  <% if signed_in? %>
	    <li><%= link_to "Profile", current_user %></li>
	    <li><%= link_to "Users", users_path %></li>
	    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	  <% end %>
	  <li><%= link_to "FAQ", faq_path %></li>
	  <% if signed_in? %>
	    <li><%= link_to "Sign Out", signout_path %></li>
	  <% else %>
	    <li><%= link_to "Sign In", signin_path %></li>
	  <% end %>
	</ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets'%>
  <%= javascript_include_tag :defaults %>
</head>
<body>
  <div class = "container">
    <%= render 'layouts/header'%>
    <section class = "round">
	<% flash.each do |key, value| %>
	  <div class="flash <%= key %>"><%= value %></div>
	<% end %>
    <%= yield %>
    </section>
	<%= render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Because we all could use some support from time to time. Whether we want to rant or we want to rave, ramples.com is a safe place to do both as well as be comforted and supported by those close to us.
After all, ramples.com is the place to rant and rave!</p>
<p>Our website will allow you to:
<ul>

	<li>Share with everyone the awesome deal you just found at your favorite store.</li>
	<li>Share a rant with only those you have selected to support you, and request support in your time of need.</li>

</ul>
</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Feel free to use the form below to send us a quick email. We will respond as quickly as we possibly can. We appreciate your patronage!</p>

app/views/pages/faq.erb
<h1>FAQ</h1>
<p>Welcome to our Frequently Asked Questions (FAQs).</p>
<p>We will strive to keep this updated with relevant information. </p>

app/views/pages/home.html.erb
<h1>ramples.com</h1>
<p>Ramples can be rants. Ramples can be raves. Regardless, ramples.com is the go-to place to help navigate through life's ups and downs.</p>
<% if !signed_in? %>
  <%= link_to "Sign Up Now!", signup_path, :class => "signup_button round"%>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
	  <%= pluralize(@user.errors.count, "error") %>
	  prohibited this user from being saved:
	</h2>
	<p>There were problems with the following fields:</p>
	<ul>
	<% @user.errors.full_messages.each do |message| %>
	  <li><%= message %></li>
	<% end %>
	</ul>
  </div>

<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>
<div class="field">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %><br />
</div>
<div class="field">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to "#{user.first_name} #{user.last_name}", user %>
  <% if current_user.admin? %>
  |
  <%= link_to "delete", user, :method => :delete, :confirm => "Confirm delete",
 							  :title => "Delete #{user.first_name} #{user.last_name}"%>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
	<%= gravatar_for @user %>
	<a href = "http://gravatar.com/emails" target=_blank>Change</a>
</div>

app/views/users/index.html.erb
<h1>Current ramples Users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
  
<% end %>

app/views/users/show.html.erb
<table class="profile" summary "Profile Information">
  <tr>
    <td class="main">
	  <h1>
        <%= gravatar_for @user %>
        <%= @user.first_name %> <%= @user.last_name %>
      </h1>
	</td>
	<td class="sidebar round">
	  <strong>Name: </strong><%= "#{@user.first_name} #{@user.last_name}" %><br />
	  <strong>URL: </strong><%= link_to user_path(@user), @user %>
	</td>
  </tr>
</table>